arb-dir: l10n
template-arb-file: intl_en.arb
output-localization-file: crimson_localizations.dart
output-class: CrimsonLocalizations
synthetic-package: false
output-dir: lib/src/generated/l10n/
untranslated-messages-file: l10n/untranslatedMessages.txt