name: crimson
description: Common validations to be used in Flutter projects.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.4
homepage: www.theyellowfactory.com


environment:
  sdk: ">=3.0.0 <4.0.0" 
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Internationalization support.
  flutter_localizations:
    sdk: flutter
  intl: any
  #end Internationalization support.
  navy:
    git: https://github.com/yellow-factory/navy.git
  email_validator: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  # Adds code generation (synthetic package) support 
  generate: false


