name: crimson
description: Common validations to be used in Flutter projects.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1
author: The Yellow Factory
homepage: www.theyellowfactory.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  navy:
    path: ../navy

dependency_overrides:
  navy:
    path: ../navy

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # Adds code generation (synthetic package) support 
  generate: true


